### ISSUE TITLE
Feature idea – Show selected drinks view: Availability count (# of bottles)

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#14]
Feature idea: Show selected drinks view could show availability count (# of bottles) of each individual drink in each of the stores

**Comment by techstalgist** [comment]
Requirement partially implemented in https://github.com/timoh/craftbeer/commit/97b31cfe513731632999eccfe20d2de63ab5b3d5

Now the problem is that StoresPage has too much content. The stores with all drinks are now shown twice. It might be enough to show them only once (for instance, the availability counts could be shown in the first table that simply lists the stores with all selected drinks).

**Comment by techstalgist** [comment]
The problem mentioned above is now "fixed" in https://github.com/timoh/craftbeer/commit/5e6363673af4db4e7dddfe0fbc870a9fa271b251. I simply removed the first table.
